import { useQuery, useMutation, useQueryClient } from "@tanstack/react-query";
import { supabase } from "@/integrations/supabase/client";
import { toast } from "sonner";
import type { Tables, TablesInsert, TablesUpdate, Enums } from "@/integrations/supabase/types";

export type DbReservationStatus = Enums<"reservation_status">;
export type DbReservation = Tables<"reservations">;
export type ReservationInsert = TablesInsert<"reservations">;
export type ReservationUpdate = TablesUpdate<"reservations">;

export interface ReservationWithDetails extends DbReservation {
  rooms: {
    id: string;
    number: string;
    type: string;
    price_per_night: number;
  } | null;
  guests: {
    id: string;
    name: string;
    email: string;
    phone: string | null;
  } | null;
}

// Fetch all reservations with room and guest details
export function useReservations() {
  return useQuery({
    queryKey: ["reservations"],
    queryFn: async () => {
      const { data, error } = await supabase
        .from("reservations")
        .select(`
          *,
          rooms:room_id (id, number, type, price_per_night),
          guests:guest_id (id, name, email, phone)
        `)
        .order("check_in", { ascending: false });
      
      if (error) throw error;
      return data as ReservationWithDetails[];
    },
  });
}

// Fetch reservations for a specific date range
export function useReservationsByDateRange(startDate: string, endDate: string) {
  return useQuery({
    queryKey: ["reservations", "range", startDate, endDate],
    queryFn: async () => {
      const { data, error } = await supabase
        .from("reservations")
        .select(`
          *,
          rooms:room_id (id, number, type, price_per_night),
          guests:guest_id (id, name, email, phone)
        `)
        .gte("check_out", startDate)
        .lte("check_in", endDate)
        .not("status", "eq", "cancelled");
      
      if (error) throw error;
      return data as ReservationWithDetails[];
    },
    enabled: !!startDate && !!endDate,
  });
}

// Fetch single reservation
export function useReservation(id: string | undefined) {
  return useQuery({
    queryKey: ["reservations", id],
    queryFn: async () => {
      if (!id) return null;
      const { data, error } = await supabase
        .from("reservations")
        .select(`
          *,
          rooms:room_id (id, number, type, price_per_night),
          guests:guest_id (id, name, email, phone)
        `)
        .eq("id", id)
        .maybeSingle();
      
      if (error) throw error;
      return data as ReservationWithDetails | null;
    },
    enabled: !!id,
  });
}

// Create reservation - confirmation_code is generated by trigger
export function useCreateReservation() {
  const queryClient = useQueryClient();
  
  return useMutation({
    mutationFn: async (reservation: {
      room_id: string;
      guest_id: string;
      check_in: string;
      check_out: string;
      total_value: number;
      adults?: number;
      children?: number;
      status?: DbReservationStatus;
      payment_method?: string | null;
      payment_status?: string | null;
      special_requests?: string | null;
      notes?: string | null;
    }) => {
      // Generate a temporary confirmation code - the trigger will override it
      const tempCode = `RES-${Date.now().toString(36).toUpperCase()}`;
      
      const { data, error } = await supabase
        .from("reservations")
        .insert({
          ...reservation,
          confirmation_code: tempCode,
        })
        .select()
        .single();
      
      if (error) throw error;
      return data;
    },
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ["reservations"] });
      queryClient.invalidateQueries({ queryKey: ["rooms"] });
      toast.success("Reserva criada com sucesso!");
    },
    onError: (error: Error) => {
      toast.error(`Erro ao criar reserva: ${error.message}`);
    },
  });
}

// Update reservation
export function useUpdateReservation() {
  const queryClient = useQueryClient();
  
  return useMutation({
    mutationFn: async ({ id, ...reservation }: ReservationUpdate & { id: string }) => {
      const { data, error } = await supabase
        .from("reservations")
        .update(reservation)
        .eq("id", id)
        .select()
        .single();
      
      if (error) throw error;
      return data;
    },
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ["reservations"] });
      queryClient.invalidateQueries({ queryKey: ["rooms"] });
      toast.success("Reserva atualizada com sucesso!");
    },
    onError: (error: Error) => {
      toast.error(`Erro ao atualizar reserva: ${error.message}`);
    },
  });
}

// Update reservation status
export function useUpdateReservationStatus() {
  const queryClient = useQueryClient();
  
  return useMutation({
    mutationFn: async ({ id, status }: { id: string; status: DbReservationStatus }) => {
      const { data, error } = await supabase
        .from("reservations")
        .update({ status })
        .eq("id", id)
        .select()
        .single();
      
      if (error) throw error;
      return data;
    },
    onSuccess: (_, { status }) => {
      queryClient.invalidateQueries({ queryKey: ["reservations"] });
      queryClient.invalidateQueries({ queryKey: ["rooms"] });
      
      const messages: Record<DbReservationStatus, string> = {
        pending: "Reserva marcada como pendente",
        confirmed: "Reserva confirmada com sucesso!",
        checked_in: "Check-in realizado com sucesso!",
        checked_out: "Check-out realizado com sucesso!",
        cancelled: "Reserva cancelada",
      };
      toast.success(messages[status]);
    },
    onError: (error: Error) => {
      toast.error(`Erro ao atualizar status: ${error.message}`);
    },
  });
}

// Delete/Cancel reservation
export function useDeleteReservation() {
  const queryClient = useQueryClient();
  
  return useMutation({
    mutationFn: async (id: string) => {
      const { error } = await supabase
        .from("reservations")
        .delete()
        .eq("id", id);
      
      if (error) throw error;
    },
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ["reservations"] });
      queryClient.invalidateQueries({ queryKey: ["rooms"] });
      toast.success("Reserva excluída com sucesso!");
    },
    onError: (error: Error) => {
      toast.error(`Erro ao excluir reserva: ${error.message}`);
    },
  });
}

// Check room availability for date range
export function useCheckAvailability(roomId: string, checkIn: string, checkOut: string, excludeReservationId?: string) {
  return useQuery({
    queryKey: ["availability", roomId, checkIn, checkOut, excludeReservationId],
    queryFn: async () => {
      let query = supabase
        .from("reservations")
        .select("id")
        .eq("room_id", roomId)
        .not("status", "in", "(cancelled,checked_out)")
        .or(`and(check_in.lte.${checkOut},check_out.gte.${checkIn})`);
      
      if (excludeReservationId) {
        query = query.neq("id", excludeReservationId);
      }
      
      const { data, error } = await query;
      
      if (error) throw error;
      return data.length === 0; // true if available
    },
    enabled: !!roomId && !!checkIn && !!checkOut,
  });
}
