-- Heavy audit hardening: close SaaS control-plane gaps, prevent forged audit records,
-- require valid subscriptions, and support safe multi-organization users.

-- 1) Control-plane tables must be protected by RLS.
ALTER TABLE public.saas_plans ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.organization_subscriptions ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "public read plans" ON public.saas_plans;
DROP POLICY IF EXISTS "authenticated read plans" ON public.saas_plans;
DROP POLICY IF EXISTS "platform manage plans" ON public.saas_plans;
CREATE POLICY "public read active plans" ON public.saas_plans
  FOR SELECT TO anon, authenticated USING (active = true OR public.is_platform_admin());
CREATE POLICY "platform manage plans" ON public.saas_plans
  FOR ALL TO authenticated
  USING (public.is_platform_admin())
  WITH CHECK (public.is_platform_admin());

DROP POLICY IF EXISTS "members read subscription" ON public.organization_subscriptions;
DROP POLICY IF EXISTS "platform/admin manage subscription" ON public.organization_subscriptions;
CREATE POLICY "members read subscription" ON public.organization_subscriptions
  FOR SELECT TO authenticated USING (public.can_access_org(organization_id));
CREATE POLICY "platform manage subscription" ON public.organization_subscriptions
  FOR ALL TO authenticated
  USING (public.is_platform_admin())
  WITH CHECK (public.is_platform_admin());
CREATE POLICY "org admins update own subscription metadata" ON public.organization_subscriptions
  FOR UPDATE TO authenticated
  USING (public.is_org_admin(organization_id))
  WITH CHECK (public.is_org_admin(organization_id));

-- 2) A normal tenant admin must never be able to create another super_admin.
DROP POLICY IF EXISTS "admins manage memberships" ON public.organization_members;
CREATE POLICY "platform admins manage memberships" ON public.organization_members
  FOR ALL TO authenticated
  USING (public.is_platform_admin())
  WITH CHECK (public.is_platform_admin());
CREATE POLICY "tenant admins manage non platform roles" ON public.organization_members
  FOR INSERT TO authenticated
  WITH CHECK (
    public.is_org_admin(organization_id)
    AND role IN ('admin','gerente','recepcao','caixa','governanca')
  );
CREATE POLICY "tenant admins update non platform roles" ON public.organization_members
  FOR UPDATE TO authenticated
  USING (public.is_org_admin(organization_id))
  WITH CHECK (
    public.is_org_admin(organization_id)
    AND role IN ('admin','gerente','recepcao','caixa','governanca')
  );
CREATE POLICY "tenant admins remove members" ON public.organization_members
  FOR DELETE TO authenticated
  USING (public.is_org_admin(organization_id));

-- 3) Audit logs are append-only and must be generated by trusted server/database code.
DROP POLICY IF EXISTS "members write org audit" ON public.organization_audit_log;
REVOKE INSERT, UPDATE, DELETE ON public.organization_audit_log FROM anon, authenticated;

-- 4) Keep the canonical audit log tenant-scoped and prevent NULL tenant records.
DO $$
BEGIN
  IF EXISTS (SELECT 1 FROM public.audit_log WHERE organization_id IS NULL) THEN
    RAISE NOTICE 'audit_log contains legacy rows without organization_id; they remain readable only to tenant admins when organization_id is present';
  END IF;
END $$;

-- 5) Active organization for users belonging to multiple hotels.
CREATE TABLE IF NOT EXISTS public.user_active_organization (
  user_id UUID PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
  organization_id UUID NOT NULL REFERENCES public.organizations(id) ON DELETE CASCADE,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
ALTER TABLE public.user_active_organization ENABLE ROW LEVEL SECURITY;

CREATE POLICY "users read own active organization" ON public.user_active_organization
  FOR SELECT TO authenticated USING (user_id = auth.uid());
CREATE POLICY "users set own active organization" ON public.user_active_organization
  FOR INSERT TO authenticated
  WITH CHECK (user_id = auth.uid() AND public.is_org_member(organization_id));
CREATE POLICY "users update own active organization" ON public.user_active_organization
  FOR UPDATE TO authenticated
  USING (user_id = auth.uid())
  WITH CHECK (user_id = auth.uid() AND public.is_org_member(organization_id));

CREATE OR REPLACE FUNCTION public.current_organization_id()
RETURNS UUID LANGUAGE sql STABLE SECURITY DEFINER SET search_path=public AS $$
  SELECT COALESCE(
    (SELECT uao.organization_id
     FROM public.user_active_organization uao
     WHERE uao.user_id = auth.uid()
       AND public.is_org_member(uao.organization_id)),
    (SELECT om.organization_id
     FROM public.organization_members om
     WHERE om.user_id = auth.uid()
     ORDER BY om.created_at
     LIMIT 1)
  );
$$;

-- 6) Subscription status is mandatory for operational mutations.
CREATE OR REPLACE FUNCTION public.organization_can_operate(_org UUID)
RETURNS BOOLEAN LANGUAGE sql STABLE SECURITY DEFINER SET search_path=public AS $$
  SELECT EXISTS (
    SELECT 1
    FROM public.organizations o
    JOIN public.organization_subscriptions s ON s.organization_id = o.id
    WHERE o.id = _org
      AND o.status <> 'suspended'
      AND s.status IN ('trial','active')
      AND (s.status = 'active' OR s.trial_ends_at IS NULL OR s.trial_ends_at > now())
      AND (s.current_period_end IS NULL OR s.current_period_end > now() OR s.status = 'trial')
  );
$$;

-- 7) Backfill a trial subscription for existing tenants that had no subscription.
DO $$
DECLARE
  v_plan UUID;
BEGIN
  SELECT id INTO v_plan FROM public.saas_plans WHERE code = 'professional' AND active = true LIMIT 1;
  IF v_plan IS NOT NULL THEN
    INSERT INTO public.organization_subscriptions (
      organization_id, plan_id, status, billing_cycle, trial_ends_at,
      current_period_start, current_period_end
    )
    SELECT o.id, v_plan, 'trial', 'monthly', now() + interval '14 days', now(), now() + interval '14 days'
    FROM public.organizations o
    LEFT JOIN public.organization_subscriptions s ON s.organization_id = o.id
    WHERE s.organization_id IS NULL
    ON CONFLICT (organization_id) DO NOTHING;
  END IF;
END $$;

-- 8) A tenant admin can only update allowed subscription metadata; billing state is platform-owned.
CREATE OR REPLACE FUNCTION public.prevent_tenant_billing_state_change()
RETURNS TRIGGER LANGUAGE plpgsql AS $$
BEGIN
  IF NOT public.is_platform_admin() THEN
    IF NEW.plan_id IS DISTINCT FROM OLD.plan_id
       OR NEW.status IS DISTINCT FROM OLD.status
       OR NEW.billing_cycle IS DISTINCT FROM OLD.billing_cycle
       OR NEW.trial_ends_at IS DISTINCT FROM OLD.trial_ends_at
       OR NEW.current_period_start IS DISTINCT FROM OLD.current_period_start
       OR NEW.current_period_end IS DISTINCT FROM OLD.current_period_end
       OR NEW.external_customer_id IS DISTINCT FROM OLD.external_customer_id
       OR NEW.external_subscription_id IS DISTINCT FROM OLD.external_subscription_id THEN
      RAISE EXCEPTION 'Billing state is managed by the platform';
    END IF;
  END IF;
  RETURN NEW;
END;
$$;
DROP TRIGGER IF EXISTS prevent_tenant_billing_state_change ON public.organization_subscriptions;
CREATE TRIGGER prevent_tenant_billing_state_change
BEFORE UPDATE ON public.organization_subscriptions
FOR EACH ROW EXECUTE FUNCTION public.prevent_tenant_billing_state_change();

-- 9) Prevent platform-admin privilege escalation through tenant role APIs.
CREATE OR REPLACE FUNCTION public.prevent_platform_role_assignment()
RETURNS TRIGGER LANGUAGE plpgsql AS $$
BEGIN
  IF NEW.role = 'super_admin' AND NOT public.is_platform_admin() THEN
    RAISE EXCEPTION 'Only platform administrators can assign super_admin';
  END IF;
  RETURN NEW;
END;
$$;
DROP TRIGGER IF EXISTS prevent_platform_role_assignment ON public.organization_members;
CREATE TRIGGER prevent_platform_role_assignment
BEFORE INSERT OR UPDATE ON public.organization_members
FOR EACH ROW EXECUTE FUNCTION public.prevent_platform_role_assignment();

-- 10) Updated indexes for common tenant isolation queries.
CREATE INDEX IF NOT EXISTS user_active_organization_org_idx ON public.user_active_organization(organization_id);
CREATE INDEX IF NOT EXISTS organization_members_org_role_idx ON public.organization_members(organization_id, role);
CREATE INDEX IF NOT EXISTS reservations_org_dates_idx ON public.reservations(organization_id, check_in, check_out);

GRANT EXECUTE ON FUNCTION public.current_organization_id() TO authenticated;
GRANT EXECUTE ON FUNCTION public.organization_can_operate(UUID) TO authenticated;
